services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=Sagar123
      - DB_NAME=banking
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sagar123
      POSTGRES_DB: banking
    ports:
      - "5432:5432"

  test_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sagar123
      POSTGRES_DB: banking_test
    ports:
      - "5433:5432"